"""
reporting.py -- generates RESULTS.md, the running scorecard (2026-09-07, PR 6).

WHAT IT IS. A pure renderer, no tool access. The orchestrating session
fetches the account snapshot and Robinhood's own realized P&L / trade
history via the MCP tools and passes them in as JSON; this module folds
them together with trade_log.jsonl and writes RESULTS.md.

RESULTS.md is the "how is the bot doing" document -- a scorecard plus a
trade ledger -- as opposed to TRADE_LOG.md (render_trade_log.py), which is
the raw event feed. Robinhood's numbers are the source of truth for money;
the trade log is the source of truth for *why* each trade was taken.

WHY A SEPARATE COMMIT STEP. The scheduled tasks run in a cloud workspace
that is not a push-enabled git checkout, so RESULTS.md written there is not
automatically on GitHub. Two ways to surface it:
  * the Market-Close task embeds RESULTS.md's scorecard in its notification
    (so you see it even with no git), and
  * `python3 reporting.py --commit` -- run wherever a push-enabled checkout
    exists (an interactive session, or the task IF its container is given
    push credentials) -- does `git add RESULTS.md && git commit && git push`.

INPUTS (all optional; the report degrades to what it's given)
  --now-utc ISO8601
  --realized-json '{"today":..,"week":..,"month":..,"all":..,
                    "trades_week":..,"trades_month":..,"win_rate":..}'
        from get_realized_pnl over day/week/month/all spans + (optionally)
        a per-trade win rate the caller computed from get_pnl_trade_history.
  --closed-trades-json '[{"symbol","option_type","strike","expiration",
        "opened_at","closed_at","entry_price","exit_price","contracts",
        "realized_pnl","exit_reason"}, ...]'
        recent closed trades (from get_pnl_trade_history or reconstructed
        from the log). Drives the ledger and the fallback win rate.
  --account-json '{"total_value","buying_power","options_value",
        "open_positions":[{"symbol","strike","option_type","expiration",
        "quantity","average_price","current_mark"}]}'
  --commit          also git add/commit/push RESULTS.md

USAGE
  python3 reporting.py --now-utc 2026-09-07T20:05:00Z \
      --realized-json '{...}' --closed-trades-json '[...]' --account-json '{...}'
"""
import argparse, json, os, subprocess, sys
from collections import Counter
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, '/home/claude/smc_bot')
sys.path.insert(0, '/home/claude/smc_bot/diag/backtest')
from trade_log import read_all

REPO_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE_DIR = '/home/claude/smc_bot/diag/backtest'
# RESULTS.md is written to the repo checkout when this runs from one (so
# --commit works), else to the task workspace.
OUT_PATH = os.path.join(REPO_DIR, 'RESULTS.md')


def _f(x, default=0.0):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


def _money(x):
    v = _f(x)
    return f"${v:+,.2f}"


def _day(iso):
    return (iso or "")[:10] or "?"


def _minutes(a, b):
    try:
        da = datetime.fromisoformat(a.replace("Z", "+00:00"))
        db = datetime.fromisoformat(b.replace("Z", "+00:00"))
        return (db - da).total_seconds() / 60.0
    except Exception:
        return None


def _win_stats(closed):
    wins = [t for t in closed if _f(t.get("realized_pnl")) > 0]
    losses = [t for t in closed if _f(t.get("realized_pnl")) < 0]
    n = len(wins) + len(losses)
    rate = (len(wins) / n) if n else None
    avg_win = (sum(_f(t["realized_pnl"]) for t in wins) / len(wins)) if wins else 0.0
    avg_loss = (sum(_f(t["realized_pnl"]) for t in losses) / len(losses)) if losses else 0.0
    return rate, avg_win, avg_loss, len(wins), len(losses)


def build_results(events, now_utc, realized=None, closed_trades=None, account=None):
    realized = realized or {}
    closed_trades = closed_trades or []
    account = account or {}
    today = _day(now_utc)

    L = []
    L.append("# Trading Pipeline -- Results")
    L.append("")
    L.append(f"_Auto-generated by `reporting.py` at {(now_utc or '').replace('T', ' ')[:16]} UTC. "
             "Do not edit -- re-run the script. Robinhood's realized P&L is the source of "
             "truth for money; the trade log is the source of truth for why._")
    L.append("")

    if not events and not realized and not closed_trades and not account:
        L.append("_No data yet._ The scheduled tasks will fill this in: the Market-Close "
                 "task runs `reporting.py` with the day's Robinhood P&L and account "
                 "snapshot, and every proposal / execution / exit is logged as it happens.")
        L.append("")
        return "\n".join(L) + "\n"

    # ---- scorecard ----
    L.append("## Scorecard")
    L.append("")
    L.append("| window | realized P&L | closing trades |")
    L.append("|---|---|---|")
    L.append(f"| today | {_money(realized.get('today'))} | {realized.get('trades_today', '?')} |")
    L.append(f"| last 7 days | {_money(realized.get('week'))} | {realized.get('trades_week', '?')} |")
    L.append(f"| last 30 days | {_money(realized.get('month'))} | {realized.get('trades_month', '?')} |")
    L.append(f"| all time | {_money(realized.get('all'))} | {realized.get('trades_all', '?')} |")
    L.append("")

    rate = realized.get("win_rate")
    if rate is None and closed_trades:
        rate, aw, al, nw, nl = _win_stats(closed_trades)
        if rate is not None:
            L.append(f"**Win rate (last {nw + nl} closed):** {rate:.0%}  "
                     f"({nw}W / {nl}L, avg win {_money(aw)}, avg loss {_money(al)})")
            L.append("")
    elif rate is not None:
        L.append(f"**Win rate:** {_f(rate) * 100:.0f}%")
        L.append("")

    # ---- account ----
    if account:
        L.append("## Account")
        L.append("")
        L.append(f"- Value: **${_f(account.get('total_value')):,.2f}**  "
                 f"(buying power ${_f(account.get('buying_power')):,.2f}, "
                 f"options ${_f(account.get('options_value')):,.2f})")
        pos = account.get("open_positions") or []
        if pos:
            L.append(f"- Open positions ({len(pos)}):")
            for p in pos:
                mark = p.get("current_mark")
                avg = _f(p.get("average_price"))
                pl = ""
                if mark is not None and avg:
                    pct = (_f(mark) / avg - 1) * 100
                    pl = f", now ${_f(mark):.2f} ({pct:+.0f}%)"
                L.append(f"  - {p.get('quantity', 1)}x {p.get('symbol')} ${p.get('strike')} "
                         f"{p.get('option_type')} exp {p.get('expiration')} @ ${avg:.2f}{pl}")
        else:
            L.append("- Open positions: none")
        L.append("")

    # ---- today's pipeline activity ----
    todays = [e for e in events if _day(e.get("logged_at_utc")) == today]
    c = Counter(e.get("event") for e in todays)
    L.append("## Today")
    L.append("")
    if todays:
        L.append(f"- Proposals prepared: {c.get('proposal_prepared', 0)}  "
                 f"(rejected on risk checks: {c.get('proposal_rejected', 0)}, "
                 f"signal-only: {c.get('signal_only_not_executed', 0)}, "
                 f"expired unconfirmed: {c.get('order_expired', 0)})")
        L.append(f"- Entries executed: {c.get('order_confirmed_executed', 0)}")
        L.append(f"- Exit proposals: {c.get('exit_proposed', 0)}  "
                 f"(expired: {c.get('exit_expired', 0)})")
        L.append(f"- Positions closed: {c.get('position_closed', 0)}")
    else:
        L.append("- No pipeline activity logged today.")
    L.append("")

    # ---- trade ledger ----
    if closed_trades:
        L.append("## Recent closed trades")
        L.append("")
        L.append("| closed | symbol | contract | in | entry | exit | P&L | hold | reason |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for t in sorted(closed_trades, key=lambda x: x.get("closed_at", ""), reverse=True)[:25]:
            hold = _minutes(t.get("opened_at", ""), t.get("closed_at", ""))
            hold_s = f"{hold/60:.1f}h" if hold and hold >= 60 else (f"{hold:.0f}m" if hold else "?")
            L.append(f"| {_day(t.get('closed_at'))} | {t.get('symbol', '?')} | "
                     f"${t.get('strike', '?')} {t.get('option_type', '')} | "
                     f"{t.get('contracts', 1)} | ${_f(t.get('entry_price')):.2f} | "
                     f"${_f(t.get('exit_price')):.2f} | {_money(t.get('realized_pnl'))} | "
                     f"{hold_s} | {t.get('exit_reason', '')} |")
        L.append("")

    # ---- reconciliation ----
    log_closed = [e for e in events if e.get("event") == "position_closed"]
    log_total = sum(_f(e.get("realized_pnl")) for e in log_closed)
    if realized.get("all") is not None:
        rh_total = _f(realized.get("all"))
        diff = log_total - rh_total
        flag = "" if abs(diff) < 0.01 else "  ⚠️ **mismatch -- investigate**"
        L.append("## Reconciliation")
        L.append("")
        L.append(f"- Trade log realized total: {_money(log_total)} ({len(log_closed)} closes)")
        L.append(f"- Robinhood realized (all time): {_money(rh_total)}{flag}")
        L.append("")

    # ---- recent events ----
    if events:
        L.append("## Last 15 events")
        L.append("")
        for e in events[-15:][::-1]:
            ts = (e.get("logged_at_utc") or "").replace("T", " ")[:16]
            sym = e.get("symbol") or e.get("pair") or ""
            L.append(f"- `{ts}` **{e.get('event')}** {sym} {e.get('reason', '') or e.get('note', '')}".rstrip())
        L.append("")

    L.append("---")
    L.append("_Nothing in this pipeline places an order. Every entry and exit is confirmed by hand._")
    return "\n".join(L) + "\n"


def git_commit_results(path=OUT_PATH):
    """git add/commit/push RESULTS.md. Best-effort -- prints and returns
    False on any failure (no push creds, not a repo, nothing changed)."""
    rel = os.path.relpath(path, REPO_DIR)
    try:
        subprocess.run(["git", "-C", REPO_DIR, "add", rel], check=True, capture_output=True)
        st = subprocess.run(["git", "-C", REPO_DIR, "status", "--porcelain", rel],
                            capture_output=True, text=True)
        if not st.stdout.strip():
            print("RESULTS.md unchanged -- nothing to commit")
            return False
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        subprocess.run(["git", "-C", REPO_DIR, "commit", "-m", f"results: update RESULTS.md ({stamp})"],
                       check=True, capture_output=True)
        subprocess.run(["git", "-C", REPO_DIR, "push"], check=True, capture_output=True)
        print("committed and pushed RESULTS.md")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError) as ex:
        out = getattr(ex, "stderr", b"")
        print(f"could not commit RESULTS.md ({ex}); {out.decode() if isinstance(out, bytes) else out}".strip())
        print("-> RESULTS.md is still written locally; commit it from a push-enabled checkout.")
        return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--now-utc", default=datetime.now(timezone.utc).isoformat())
    ap.add_argument("--realized-json", default="{}")
    ap.add_argument("--realized-file")
    ap.add_argument("--closed-trades-json", default="[]")
    ap.add_argument("--closed-trades-file")
    ap.add_argument("--account-json", default="{}")
    ap.add_argument("--account-file")
    ap.add_argument("--commit", action="store_true")
    ap.add_argument("--out", default=OUT_PATH)
    args = ap.parse_args()

    def _load(inline, path, default):
        if path:
            try:
                return json.load(open(path))
            except (FileNotFoundError, json.JSONDecodeError):
                return default
        return json.loads(inline)

    realized = _load(args.realized_json, args.realized_file, {})
    closed = _load(args.closed_trades_json, args.closed_trades_file, [])
    account = _load(args.account_json, args.account_file, {})

    md = build_results(read_all(), args.now_utc, realized, closed, account)
    with open(args.out, "w") as f:
        f.write(md)
    print(f"wrote {args.out} ({len(md)} chars)")

    if args.commit:
        git_commit_results(args.out)

    # Print the scorecard block for the task to drop into its notification.
    lines = md.splitlines()
    end = len(lines)
    for marker in ("## Account", "## Today"):
        if marker in lines:
            end = lines.index(marker)
            break
    print("\n--- scorecard (for the notification) ---")
    print("\n".join(lines[:end]).strip())


if __name__ == "__main__":
    main()
