"""
Wednesday-only alternate strategy (REVISION 17, 2026-08-30), per explicit
user request: SMC runs Mon/Tue/Thu/Fri; this VWAP-200/DMI/ADX trend
screener runs Wednesday ALONE (its own scheduled trigger, SMC's trigger
excludes Wednesday). SIGNAL-ONLY, read-only, same architecture as
dry_run_check.py -- this script is the evaluation engine, not the fetch
layer. The calling/orchestrating session fetches hourly bars via
mcp__RBH__get_equity_historicals for WATCHLIST (batched <=10 symbols) and
stages them as raw JSON under RAW_DIR (see below) before this script runs.

REVISION 17 change (explicit user request, 2026-08-30): WATCHLIST is no
longer a hand-picked 24-symbol list. It now loads from watchlist_universe.json,
a live snapshot generated by a Robinhood scan (mcp__RBH__create_scan /
run_scan, scan_id in that file) filtered to Stock+ETF, price >= $5, average
30-day options volume >= 500 -- i.e. "run the AND-gate against everything
that clears a basic liquidity/optionability bar, and let whatever passes,
pass," rather than a pre-selected list. Tested live: loosening every filter
on that scan (removing the price floor, the options-volume floor, adding
CRYPTO/FUTURE asset types) still capped out at ~395-400 total matches --
that appears to be a hard ceiling on Robinhood's own scanner backend, not a
limit imposed here. 399 symbols were fetched and verified for this revision
(see watchlist_universe.json). If that file is missing or empty, this falls
back to the original 24-symbol FALLBACK_WATCHLIST below so the script never
silently runs on nothing.

Strategy logic (adapted from a user-supplied script; fixed to remove two
real defects before touching real money):
  1. Original used yfinance (an unofficial, scraped data source) -- this
     version consumes only pre-staged Robinhood historicals, same pattern
     as the rest of this codebase.
  2. Original wrote fabricated "estimated_option_ask" prices straight to
     pending_live_orders.json with a raw `open(..., "w")` (overwriting
     the file outright, no check for an existing pending proposal). This
     version does neither: it only detects and logs raw signals here.
     Turning a hit into an actual proposal is the calling session's job,
     using the EXACT SAME steps 9a-9i / live_prepare_order.py pipeline
     the SMC bot uses (real quotes, real contract_selector.select_contract()
     ATM/OTM-delta resolution, real live_risk_checks.py gates, and
     live_prepare_order.py's own APPEND-not-overwrite write to
     pending_live_orders.json, which also already enforces the
     19:30 UTC execution cutoff via check_execution_time()). This script
     never touches pending_live_orders.json.

REVISION 18 (2026-09-07), per explicit user request -- INTRADAY REBUILD.
The strategy is now a same-day trade (see docs/ENTRY_SPEC.md section 2), so the
hourly machinery is replaced:
  - Bars: 5-minute (was hourly). The calling session stages the PRIOR
    session plus today, so ADX(14)/ATR(14) are warm from the open instead
    of only stabilising mid-morning.
  - VWAP: session_vwap() -- a session-anchored VWAP that resets at each UTC
    day's first bar -- replaces the rolling 200-bar VWAP (which, on hourly
    bars, was ~30 trading days of context: a swing-trend filter, not an
    intraday one). Feeding it the prior session does not contaminate today's
    anchor: each day is its own cumulative VWAP.

Entry conditions (all three must hold on the latest CLOSED 5-minute bar,
and the cross must be between two of TODAY's bars):
  - Session-VWAP cross: close crosses the session VWAP vs. the previous
    5-minute bar. Up-cross -> call, down-cross -> put.
  - DMI alignment: +DI > -DI for a bullish cross, -DI > +DI for a bearish
    cross (14-period, Wilder-smoothed).
  - Trend strength: ADX(14) > 20.

On a qualifying signal, computes (informational only -- this script does
NOT enforce or place any stop/target; exits are managed separately, see
docs/EXIT_SPEC.md -- these numbers are reference for the calling session):
  stop_distance = 1.5 * ATR(14, 5-min)     (tighter than the old 2.5x, intraday)
  stop_loss   = close -/+ stop_distance     (bullish/bearish)
  take_profit = close +/- 2 * stop_distance

HARD RULE: same as every other script in this pipeline -- this file calls
NO broker/order tools whatsoever. It cannot place, review, or prepare a
trade; it only detects and logs a raw technical signal.
"""
import json, sys, os
from datetime import datetime, timezone
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vwap_dmi_indicators import session_vwap, adx_dmi, atr

FALLBACK_WATCHLIST = [
    "AMD", "NVDA", "AAPL", "PLTR", "MSFT", "TSLA", "AMZN", "GOOGL",
    "COIN", "SOFI", "HOOD", "MARA", "ROKU", "PYPL", "F", "GM",
    "SPY", "QQQ", "IWM", "XLF", "XLE", "SMH", "TQQQ", "SQQQ",
]

UNIVERSE_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "watchlist_universe.json")


def load_universe(path: str = UNIVERSE_FILE, fallback=None) -> list:
    """Loads the live, scan-generated symbol universe (see REVISION 17 note
    above). Falls back to the small static list only if the universe file
    is missing/empty -- the fallback keeps the script safe to run, it is
    not the intended production list."""
    try:
        with open(path) as f:
            data = json.load(f)
        tickers = data.get("tickers", [])
        if tickers:
            return tickers
    except (FileNotFoundError, json.JSONDecodeError):
        pass
    return list(fallback or FALLBACK_WATCHLIST)


WATCHLIST = load_universe()

BAR_INTERVAL = "5min"          # REVISION 18: the screener runs on 5-minute bars now, not hourly
VWAP_WINDOW = 200             # LEGACY -- only walkforward_wed_vwap_dmi.py (backtest of the
                             # pre-REVISION-18 hourly strategy) still reads this. The live
                             # screener uses session_vwap(), no window.
DMI_ADX_LENGTH = 14
ADX_MIN = 20.0
ATR_STOP_MULT = 1.5           # reference stop distance = ATR_STOP_MULT * ATR(14)
ATR_TARGET_MULT = 2.0        # reference target distance = ATR_TARGET_MULT * stop_distance
MIN_BARS_REQUIRED = 40        # ADX(14) needs ~2x14 bars to stabilise; a ~40-bar prior-session
                             # warm-up seed covers this from today's open
MIN_SESSION_BARS = 2         # need 2 of today's bars to detect a same-session VWAP cross

BACKTEST_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(BACKTEST_DIR, "vwap_dmi_raw")
LOG_PATH = os.path.join(BACKTEST_DIR, "vwap_dmi_log.jsonl")


def _load_bars_for_symbol(sym: str, raw_dir: str) -> pd.DataFrame:
    """Consolidates every staged batch file that contains this symbol's
    5-minute bars (prior session + today) into one sorted, deduped DataFrame."""
    frames = []
    if not os.path.isdir(raw_dir):
        return pd.DataFrame()
    for fname in sorted(os.listdir(raw_dir)):
        if not fname.endswith(".json"):
            continue
        try:
            d = json.load(open(os.path.join(raw_dir, fname)))
        except Exception:
            continue
        for r in d.get("data", {}).get("results", []):
            if r.get("symbol") != sym:
                continue
            bars = r.get("bars", [])
            if bars:
                frames.append(pd.DataFrame(bars))
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    df = df.rename(columns={"open_price": "open", "close_price": "close",
                             "high_price": "high", "low_price": "low"})
    for col in ["open", "high", "low", "close"]:
        df[col] = df[col].astype(float)
    df["volume"] = df["volume"].astype(float)
    df["begins_at"] = pd.to_datetime(df["begins_at"])
    df = df.drop_duplicates(subset="begins_at").sort_values("begins_at").reset_index(drop=True)
    return df


def evaluate(raw_dir: str = RAW_DIR, watchlist=None) -> list:
    watchlist = watchlist or WATCHLIST
    hits = []
    for sym in watchlist:
        df = _load_bars_for_symbol(sym, raw_dir)
        if len(df) < MIN_BARS_REQUIRED:
            continue

        df["svwap"] = session_vwap(df, ts_col="begins_at")
        dmi = adx_dmi(df, length=DMI_ADX_LENGTH)
        df["adx"] = dmi["adx"]
        df["plus_di"] = dmi["plus_di"]
        df["minus_di"] = dmi["minus_di"]
        df["atr"] = atr(df, length=DMI_ADX_LENGTH)

        # Restrict the cross check to TODAY's session (the last calendar day
        # present) so a cross is never detected across the prior-session
        # boundary that only exists to warm up ADX/ATR.
        last_day = df["begins_at"].iloc[-1].normalize()
        today = df[df["begins_at"].dt.normalize() == last_day].reset_index(drop=True)
        if len(today) < MIN_SESSION_BARS:
            continue

        curr = today.iloc[-1]
        prev = today.iloc[-2]
        if pd.isna(curr["svwap"]) or pd.isna(prev["svwap"]) or pd.isna(curr["adx"]):
            continue

        close_price = float(curr["close"])
        adx_val = float(curr["adx"])
        plus_di = float(curr["plus_di"])
        minus_di = float(curr["minus_di"])
        atr_val = float(curr["atr"])

        bullish_cross = (prev["close"] <= prev["svwap"]) and (curr["close"] > curr["svwap"])
        bearish_cross = (prev["close"] >= prev["svwap"]) and (curr["close"] < curr["svwap"])

        signal_type = None
        if bullish_cross and plus_di > minus_di and adx_val > ADX_MIN:
            signal_type = "BULLISH_CALL"
            stop_distance = ATR_STOP_MULT * atr_val
            stop_loss = round(close_price - stop_distance, 2)
            take_profit = round(close_price + stop_distance * ATR_TARGET_MULT, 2)
            direction = "call"
        elif bearish_cross and minus_di > plus_di and adx_val > ADX_MIN:
            signal_type = "BEARISH_PUT"
            stop_distance = ATR_STOP_MULT * atr_val
            stop_loss = round(close_price + stop_distance, 2)
            take_profit = round(close_price - stop_distance * ATR_TARGET_MULT, 2)
            direction = "put"
        else:
            continue

        ts = curr["begins_at"]
        ts_str = ts.strftime("%Y-%m-%d %H:%M:%S+00:00") if hasattr(ts, "strftime") else str(ts)

        hits.append({
            "checked_at_utc": datetime.now(timezone.utc).isoformat(),
            "symbol": sym,
            "direction": direction,
            "signal": signal_type,
            "timestamp": ts_str,
            "entry_price": close_price,
            "session_vwap": round(float(curr["svwap"]), 4),
            "adx_14": round(adx_val, 2),
            "plus_di_14": round(plus_di, 2),
            "minus_di_14": round(minus_di, 2),
            "atr_14": round(atr_val, 4),
            "stop_loss_reference": stop_loss,
            "take_profit_reference": take_profit,
            "strategy": "SESSION_VWAP_DMI_ADX",
        })
    return hits


def log_hits(hits):
    if not hits:
        return
    with open(LOG_PATH, "a") as f:
        for h in hits:
            f.write(json.dumps(h) + "\n")


if __name__ == "__main__":
    print(f'=== Session-VWAP/DMI/ADX intraday screener (5-min) @ {datetime.now(timezone.utc).isoformat()} ===')
    print(f"Watchlist: {len(WATCHLIST)} symbols")

    hits = evaluate()
    log_hits(hits)

    if hits:
        print(f"\n*** {len(hits)} qualifying signal(s) this pass ***")
        for h in hits:
            print(f"  {h['symbol']:6s} {h['direction']:4s} [{h['signal']}] entry={h['entry_price']:.2f} "
                  f"ADX={h['adx_14']} +DI={h['plus_di_14']} -DI={h['minus_di_14']} "
                  f"ref_stop={h['stop_loss_reference']} ref_target={h['take_profit_reference']} ts={h['timestamp']}")
        print(f"\nLogged to {LOG_PATH}")
    else:
        print("\nNo qualifying VWAP/DMI signals this pass.")

    print("\nSIGNAL-ONLY -- no order-placement tool was called or is reachable from this script. "
          "stop_loss_reference/take_profit_reference are informational (this strategy, like the SMC "
          "bot, never manages exits automatically) -- the actual prepared order (if any) uses the "
          "same live_prepare_order.py hard-stop convention as every other proposal.")
