"""
Wednesday-only alternate strategy (REVISION 17, 2026-08-30), per explicit
user request: SMC runs Mon/Tue/Thu/Fri; this VWAP-200/DMI/ADX trend
screener runs Wednesday ALONE (its own scheduled trigger, SMC's trigger
excludes Wednesday). SIGNAL-ONLY, read-only, same architecture as
dry_run_check.py -- this script is the evaluation engine, not the fetch
layer. The calling/orchestrating session fetches hourly bars via
mcp__RBH__get_equity_historicals for WATCHLIST (batched <=10 symbols) and
stages them as raw JSON under RAW_DIR (see below) before this script runs.

REVISION 17 change (explicit user request, 2026-08-30): WATCHLIST is no
longer a hand-picked 24-symbol list. It now loads from watchlist_universe.json,
a live snapshot generated by a Robinhood scan (mcp__RBH__create_scan /
run_scan, scan_id in that file) filtered to Stock+ETF, price >= $5, average
30-day options volume >= 500 -- i.e. "run the AND-gate against everything
that clears a basic liquidity/optionability bar, and let whatever passes,
pass," rather than a pre-selected list. Tested live: loosening every filter
on that scan (removing the price floor, the options-volume floor, adding
CRYPTO/FUTURE asset types) still capped out at ~395-400 total matches --
that appears to be a hard ceiling on Robinhood's own scanner backend, not a
limit imposed here. 399 symbols were fetched and verified for this revision
(see watchlist_universe.json). If that file is missing or empty, this falls
back to the original 24-symbol FALLBACK_WATCHLIST below so the script never
silently runs on nothing.

Strategy logic (adapted from a user-supplied script; fixed to remove two
real defects before touching real money):
  1. Original used yfinance (an unofficial, scraped data source) -- this
     version consumes only pre-staged Robinhood historicals, same pattern
     as the rest of this codebase.
  2. Original wrote fabricated "estimated_option_ask" prices straight to
     pending_live_orders.json with a raw `open(..., "w")` (overwriting
     the file outright, no check for an existing pending proposal). This
     version does neither: it only detects and logs raw signals here.
     Turning a hit into an actual proposal is the calling session's job,
     using the EXACT SAME steps 9a-9i / live_prepare_order.py pipeline
     the SMC bot uses (real quotes, real contract_selector.select_contract()
     ATM/OTM-delta resolution, real live_risk_checks.py gates, and
     live_prepare_order.py's own APPEND-not-overwrite write to
     pending_live_orders.json, which also already enforces the
     19:30 UTC execution cutoff via check_execution_time()). This script
     never touches pending_live_orders.json.

Entry conditions (all three must hold on the latest hourly bar):
  - VWAP-200 cross: close crosses from below/above the rolling 200-bar
    VWAP to above/below it (vs. the previous bar).
  - DMI alignment: +DI > -DI for a bullish cross, -DI > +DI for a bearish
    cross (14-period, Wilder-smoothed).
  - Trend strength: ADX(14) > 20.

On a qualifying signal, computes (informational only -- this script does
NOT enforce or place any stop/target; the live bot never manages exits
automatically, same as every other strategy here -- these numbers are
for the calling session to report to the user as reference, not acted on):
  stop_distance = 2.5 * ATR(14)
  stop_loss   = close -/+ stop_distance   (bullish/bearish)
  take_profit = close +/- 3 * stop_distance

HARD RULE: same as every other script in this pipeline -- this file calls
NO broker/order tools whatsoever. It cannot place, review, or prepare a
trade; it only detects and logs a raw technical signal.
"""
import json, sys, os
from datetime import datetime, timezone
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vwap_dmi_indicators import rolling_vwap, adx_dmi, atr

FALLBACK_WATCHLIST = [
    "AMD", "NVDA", "AAPL", "PLTR", "MSFT", "TSLA", "AMZN", "GOOGL",
    "COIN", "SOFI", "HOOD", "MARA", "ROKU", "PYPL", "F", "GM",
    "SPY", "QQQ", "IWM", "XLF", "XLE", "SMH", "TQQQ", "SQQQ",
]

UNIVERSE_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "watchlist_universe.json")


def load_universe(path: str = UNIVERSE_FILE, fallback=None) -> list:
    """Loads the live, scan-generated symbol universe (see REVISION 17 note
    above). Falls back to the small static list only if the universe file
    is missing/empty -- the fallback keeps the script safe to run, it is
    not the intended production list."""
    try:
        with open(path) as f:
            data = json.load(f)
        tickers = data.get("tickers", [])
        if tickers:
            return tickers
    except (FileNotFoundError, json.JSONDecodeError):
        pass
    return list(fallback or FALLBACK_WATCHLIST)


WATCHLIST = load_universe()

VWAP_WINDOW = 200
DMI_ADX_LENGTH = 14
ADX_MIN = 20.0
MIN_BARS_REQUIRED = VWAP_WINDOW + 10  # a little buffer past the full rolling window

BACKTEST_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(BACKTEST_DIR, "vwap_dmi_raw")
LOG_PATH = os.path.join(BACKTEST_DIR, "vwap_dmi_log.jsonl")


def _load_bars_for_symbol(sym: str, raw_dir: str) -> pd.DataFrame:
    """Consolidates every staged batch file that contains this symbol's
    hourly bars into one sorted, deduped DataFrame."""
    frames = []
    if not os.path.isdir(raw_dir):
        return pd.DataFrame()
    for fname in sorted(os.listdir(raw_dir)):
        if not fname.endswith(".json"):
            continue
        try:
            d = json.load(open(os.path.join(raw_dir, fname)))
        except Exception:
            continue
        for r in d.get("data", {}).get("results", []):
            if r.get("symbol") != sym:
                continue
            bars = r.get("bars", [])
            if bars:
                frames.append(pd.DataFrame(bars))
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    df = df.rename(columns={"open_price": "open", "close_price": "close",
                             "high_price": "high", "low_price": "low"})
    for col in ["open", "high", "low", "close"]:
        df[col] = df[col].astype(float)
    df["volume"] = df["volume"].astype(float)
    df["begins_at"] = pd.to_datetime(df["begins_at"])
    df = df.drop_duplicates(subset="begins_at").sort_values("begins_at").reset_index(drop=True)
    return df


def evaluate(raw_dir: str = RAW_DIR, watchlist=None) -> list:
    watchlist = watchlist or WATCHLIST
    hits = []
    for sym in watchlist:
        df = _load_bars_for_symbol(sym, raw_dir)
        if len(df) < MIN_BARS_REQUIRED:
            continue

        df["vwap_200"] = rolling_vwap(df, window=VWAP_WINDOW, min_periods=20)
        dmi = adx_dmi(df, length=DMI_ADX_LENGTH)
        df["adx"] = dmi["adx"]
        df["plus_di"] = dmi["plus_di"]
        df["minus_di"] = dmi["minus_di"]
        df["atr"] = atr(df, length=DMI_ADX_LENGTH)

        curr = df.iloc[-1]
        prev = df.iloc[-2]
        if pd.isna(curr["vwap_200"]) or pd.isna(prev["vwap_200"]) or pd.isna(curr["adx"]):
            continue

        close_price = float(curr["close"])
        adx_val = float(curr["adx"])
        plus_di = float(curr["plus_di"])
        minus_di = float(curr["minus_di"])
        atr_val = float(curr["atr"])

        bullish_cross = (prev["close"] <= prev["vwap_200"]) and (curr["close"] > curr["vwap_200"])
        bearish_cross = (prev["close"] >= prev["vwap_200"]) and (curr["close"] < curr["vwap_200"])

        signal_type = None
        if bullish_cross and plus_di > minus_di and adx_val > ADX_MIN:
            signal_type = "BULLISH_CALL"
            stop_distance = 2.5 * atr_val
            stop_loss = round(close_price - stop_distance, 2)
            take_profit = round(close_price + stop_distance * 3.0, 2)
            direction = "call"
        elif bearish_cross and minus_di > plus_di and adx_val > ADX_MIN:
            signal_type = "BEARISH_PUT"
            stop_distance = 2.5 * atr_val
            stop_loss = round(close_price + stop_distance, 2)
            take_profit = round(close_price - stop_distance * 3.0, 2)
            direction = "put"
        else:
            continue

        ts = curr["begins_at"]
        ts_str = ts.strftime("%Y-%m-%d %H:%M:%S+00:00") if hasattr(ts, "strftime") else str(ts)

        hits.append({
            "checked_at_utc": datetime.now(timezone.utc).isoformat(),
            "symbol": sym,
            "direction": direction,
            "signal": signal_type,
            "timestamp": ts_str,
            "entry_price": close_price,
            "adx_14": round(adx_val, 2),
            "plus_di_14": round(plus_di, 2),
            "minus_di_14": round(minus_di, 2),
            "atr_14": round(atr_val, 2),
            "stop_loss_reference": stop_loss,
            "take_profit_reference": take_profit,
            "strategy": "VWAP200_DMI_ADX",
        })
    return hits


def log_hits(hits):
    if not hits:
        return
    with open(LOG_PATH, "a") as f:
        for h in hits:
            f.write(json.dumps(h) + "\n")


if __name__ == "__main__":
    print(f'=== VWAP-200/DMI/ADX Wednesday screener @ {datetime.now(timezone.utc).isoformat()} ===')
    print(f"Watchlist: {len(WATCHLIST)} symbols")

    hits = evaluate()
    log_hits(hits)

    if hits:
        print(f"\n*** {len(hits)} qualifying signal(s) this pass ***")
        for h in hits:
            print(f"  {h['symbol']:6s} {h['direction']:4s} [{h['signal']}] entry={h['entry_price']:.2f} "
                  f"ADX={h['adx_14']} +DI={h['plus_di_14']} -DI={h['minus_di_14']} "
                  f"ref_stop={h['stop_loss_reference']} ref_target={h['take_profit_reference']} ts={h['timestamp']}")
        print(f"\nLogged to {LOG_PATH}")
    else:
        print("\nNo qualifying VWAP/DMI signals this pass.")

    print("\nSIGNAL-ONLY -- no order-placement tool was called or is reachable from this script. "
          "stop_loss_reference/take_profit_reference are informational (this strategy, like the SMC "
          "bot, never manages exits automatically) -- the actual prepared order (if any) uses the "
          "same live_prepare_order.py hard-stop convention as every other proposal.")
